"""add wishlist table

Revision ID: 3a6f8b8d92ad
Revises: 1992ece1f87d
Create Date: 2025-11-02 12:00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6f8b8d92ad'
down_revision = '1992ece1f87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='unique_wishlist_user_product')
    )
    op.create_index('ix_wishlist_items_product_id', 'wishlist_items', ['product_id'], unique=False)
    op.create_index('ix_wishlist_items_user_id', 'wishlist_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wishlist_items_user_id', table_name='wishlist_items')
    op.drop_index('ix_wishlist_items_product_id', table_name='wishlist_items')
    op.drop_table('wishlist_items')
    # ### end Alembic commands ###


